steps:

# This step builds the container image.
- name: 'gcr.io/cloud-builders/docker'
  id: Build image
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME-$SHORT_SHA'
  - '.'

# This step pushes the image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  id: Push Image
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME-$SHORT_SHA'

# Deploy image to Google Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  id: Deploy Image to Cloud Run
  args:
  - 'run'
  - 'deploy'
  - 'oat-cloud-build'
  - '--image'
  - 'gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME-$SHORT_SHA'
  - '--port'
  - '8080'
  - '--region'
  - 'asia-southeast1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'